name: xarray_2021
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - s3fs==0.4.2
  - xarray==0.20.1
  - metpy==1.1.0
  - pandas==1.2.4
  - numpy==1.21.2
  - netcdf4==1.5.8
  - zarr==2.10.1
  - nc-time-axis==1.4.0
  - jupyterlab==3.2.3
  - cartopy==0.20.1
  - pythia-datasets==2021.9.21
  - matplotlib==3.4.3
  - requests==2.26.0
  - mamba==0.17.0
  - pydap==3.2.2
  - dask==2021.11.1
